IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[Company]') AND type in (N'U'))

BEGIN
CREATE TABLE [dbo].[Company](
    Id int IDENTITY(1,1) NOT NULL,
    [Name] varchar(125),
 CONSTRAINT [PK_CompanyId] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]


END